### PR TITLE
Update intro002.adoc

### PR DESCRIPTION
**Pull request by jskelin**
Fix some outdated links

### CODE REVIEW

**Review by keilw — CHANGES_REQUESTED** [review]
You can't just say "To get the Jakarta EE 8 SDK, go to ...oracle..,javaee...", either call it "Java EE" or point to another SDK if available.

**Comment by keilw** [comment]
@jskelin It seems you may not have an ECA in place aside from the phrasing issues in the proposed change, did you sign the ECA?

**Comment by jskelin** [comment]
ECA signed,
requested changes done

**Review by bshannon — CHANGES_REQUESTED** [review]
These changes seem to be going in the wrong direction.

There's a bunch of stuff in these tutorials that needs to be updated for the Jakarta EE 8 release.
No one has started that work.  Reverting these pieces to refer to Java EE 8 instead is not what we want.

The changes for Apache NetBeans seem fine.

**Comment by keilw** [comment]
It looks like the ECA is still not recognized or processed by Eclipse Foundation. Isn't the NetBeans part a bit of legacy or is NetBeans the only IDE to use for this? Of couse it doesn't have to be Eclipse IDE just because Jakarta EE is now at Eclipse, but shouldn't people have a choice if they use IntelliJ, Eclipse or NetBeans?

**Comment by gabrielbussolo** [comment]
I did a correction at eclipse-ee4j/jakartaee-firstcup#15 so I think that we can close this pull request. :smiley:

**Comment by jskelin** [comment]
.

**Pull request closed without merging**
